"""Skill Gap Detective — signature feature: matched/missing/partial skills, priorities, roadmap."""

import streamlit as st

from services import ai_service as ai
from services import database as db
from utils import ui

st.set_page_config(page_title="Skill Gap Detective — CareerPilot AI", page_icon="🧩", layout="wide")
ui.inject_css()
db.init_db()

st.title("🧩 Skill Gap Detective")
st.caption("Find exactly what you're missing for a job — and a concrete plan to close the gap.")

profile = db.get_profile()
if not ui.require_profile(profile):
    st.stop()

job = ui.job_selector_widget("skillgap")
if not ui.require_selected_job(job):
    st.stop()

st.markdown(f"### {job['title']} at {job['company']}")

existing_app = db.get_application_by_job_id(job["id"])
cached = existing_app.get("skill_gap_json") if existing_app else None

if st.button("🔄 Run Skill Gap Analysis", type="primary"):
    with st.spinner("Comparing your skills against this job's requirements..."):
        result = ai.detect_skill_gap(profile, job)
    st.session_state["skill_gap_result"] = result
    if not existing_app:
        app_id = db.add_application(job, status="Saved")
    else:
        app_id = existing_app["id"]
    db.update_application(app_id, {"skill_gap_json": result})
    cached = result

result = st.session_state.get("skill_gap_result") or cached

if not result:
    ui.empty_state("🧩", "No analysis yet", "Click **Run Skill Gap Analysis** to generate one.")
    st.stop()

if result.get("ai_warning"):
    ui.ai_error_box(result["ai_warning"])

st.markdown("#### With your current profile, you are approximately:")
ui.progress_bar(result["alignment_pct"], "Skill Alignment")
st.caption(f"📐 How this was calculated: {result['calculation_note']}")

sm = result["skill_match"]
c1, c2, c3 = st.columns(3)
with c1:
    st.markdown("##### ✓ Skills You Already Have")
    for s in sm["required_matched"]:
        st.markdown(f"- ✅ {s}")
    if not sm["required_matched"]:
        st.caption("None of the required skills matched yet.")
with c2:
    st.markdown("##### 🟡 Partially Matching")
    for s in sm["required_partial"]:
        st.markdown(f"- 🟡 {s}")
    if not sm["required_partial"]:
        st.caption("No partial matches.")
with c3:
    st.markdown("##### ✗ Missing / Nice-to-Have")
    for s in sm["required_missing"]:
        st.markdown(f"- ❌ {s} (required)")
    for s in sm["preferred_missing"]:
        st.markdown(f"- ⭐ {s} (preferred)")

st.divider()
st.markdown("#### 🎯 Learning Priority")
if not result["priorities"]:
    st.success("No gaps detected — you meet or exceed every listed skill for this job!")
else:
    for i, item in enumerate(result["priorities"], 1):
        cols = st.columns([0.5, 2, 1.5, 4])
        with cols[0]:
            st.markdown(f"**{i}.**")
        with cols[1]:
            st.markdown(f"**{item['skill']}**")
        with cols[2]:
            st.markdown(ui.priority_pill(item["priority"]), unsafe_allow_html=True)
        with cols[3]:
            roadmap_item = next((r for r in result.get("roadmap", []) if r.get("skill") == item["skill"]), None)
            if roadmap_item:
                st.caption(f"{roadmap_item.get('learning_approach','')} (~{roadmap_item.get('estimated_time','')})")
            else:
                st.caption(f"Status: {item['status']}")

    if result.get("roadmap"):
        ui.ai_badge()
        st.caption("Learning approach and time estimates generated by the AI model based on your existing skills.")

st.divider()
bc1, bc2 = st.columns(2)
with bc1:
    if st.button("📊 See Application Strength →"):
        st.switch_page("pages/06_Application_Predictor.py")
with bc2:
    if st.button("🎤 Practice interview for this job →"):
        st.switch_page("pages/07_Interview_Twin.py")
